In [1]:
# Menggunakan Numpy: pengolahan matriks
import numpy as np
list1 = [0, 1, 2, 3, 4] #tipe data list biasa saja di Python
array1d = np.array(list1)
array1d


array([0, 1, 2, 3, 4])

In [2]:
# tipe data
type(array1d)



numpy.ndarray

In [3]:
# menjumlahkan elemen array
array1d + 2


array([2, 3, 4, 5, 6])

In [11]:
# membuat array 2 dimensi
list2 = [[10, 1.5, 2.8, 3.7], [2.5, 4.56, 6.5, 8.7], [3.6, 6.7, 9.6, 12.5],]
array2d = np.array(list2)
array2d



array([[10.  ,  1.5 ,  2.8 ,  3.7 ],
       [ 2.5 ,  4.56,  6.5 ,  8.7 ],
       [ 3.6 ,  6.7 ,  9.6 , 12.5 ]])

In [8]:
# mengatur jenis data: float/int
array2d.astype('int')

array([[ 0,  1,  2,  3],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [16]:
# mengambil elemen tertentu pada array
# elemen pertama, sebanyak 1
data1 = array2d[:1, :1]
data1

array([[10.]])

In [18]:
data2 = array2d[:1, :2]
data2


array([[10. ,  1.5]])

In [20]:
# operasi: mean/min/max
array2d.mean()


1.5

In [22]:
array2d.max()

12.5

In [21]:
array2d.min()

1.5

In [24]:
# Reshape dan Flattening
## Reshape = mengubah dimensi array
## Flattening = mengubah array menjadi 1 dimensi
array2d_new_dimension = array2d.reshape(4, 3)
array2d_new_dimension


ValueError: cannot reshape array of size 12 into shape (10,2)

In [25]:
## Flattening
array2d.flatten()

array([10.  ,  1.5 ,  2.8 ,  3.7 ,  2.5 ,  4.56,  6.5 ,  8.7 ,  3.6 ,
        6.7 ,  9.6 , 12.5 ])

In [29]:
# Membuat array terisi data secara otomatis 
np.arange(100)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Membuat array terisi data secara otomatis: range tertentu 
np.arange(4, 10)


array([4, 5, 6, 7, 8, 9])

In [36]:
# Membuat array dengan jumlah pasti, dengan angka antara 1 dan 50
# sejumlah num angka
np.linspace(start=20, stop=30, num=10, dtype=int)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 30])

In [38]:
# membuat array khusus, misal array kosong (zero)
np.zeros([3, 4])



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# membuat array khusus, berisi angka 1
np.ones([3,4])



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
# membuat array dengan isi bilangan acak dengan dimensi 3x4 (3 baris, 4 kolom)
np.random.rand(3, 4)


array([[0.37212348, 0.38264056, 0.59974295, 0.52637659],
       [0.68456428, 0.00711169, 0.28156172, 0.23798866],
       [0.69286634, 0.17975489, 0.61406743, 0.08589391]])

In [46]:
# membuat array acak dengan angka keacakan antara 3 dan 5
np.random.randint(3, 100, size=[3,4])



array([[41, 24, 79, 22],
       [98, 97, 97, 51],
       [47, 21,  5, 18]])

In [47]:
# Memilih 10 data acak dari 2 pilihan
np.random.choice(['Pria', 'Wanita'], size=10 )

array(['Wanita', 'Wanita', 'Wanita', 'Pria', 'Wanita', 'Pria', 'Pria',
       'Wanita', 'Pria', 'Pria'], dtype='<U6')